jwt added, authentification added
KaplinY/Python-puzzles pull request #11
Opened 2023-04-06 01:24 UTC by KaplinY

Почему то ему не нравится мой SQL query. Приложение запускается, пользователь добавляется, но когда пытаюсь сделать аутентификацию, то выдает ошибку

2023-04-07 18:41 UTC, KaplinY commented
Финальная версия, я проверил, всё работает, в базу данных всё складывает, но вот токен надо руками копировать в хэдер

2023-04-07 19:27 UTC, s3rius requested changes

2023-04-07 19:27 UTC, s3rius commented on project1/main.py
> +                    FOREIGN_KEY VARCHAR)
Ради таких штук обычно используют ID. ID это уникальные идентификаторы объектов в таблице. Чаще всего они генерируются. Например используют инкрементирующие INTEGER или UUID.

Вот пример связки 2 таблиц.
```sql
CREATE TABLE pet_owner(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE pet(
    id SERIAL PRIMARY KEY,
    name TEXT,
    owner BIGINT,
    FOREIGN KEY(owner) REFERENCES pet_owner(id) ON DELETE CASCADE
);


INSERT INTO pet_owner(name) VALUES ('petar'), ('johan');
INSERT INTO pet(name, owner) VALUES ('barsik', 1), ('murka', 2);
```

Как ты можешь видеть, тут создаётся pet_owner и у него может быть много петов. Чтобы это хранить мы добавляем в каждого пета id его овнера. Но при объявлении мы явно говорим что id это должен быть рефернс на id из таблицы овнеров. Таким образом, если ты попробуешь вставить в pet строку со значеним owner, id которого не существует в таблице овнеров, то postgresql тебе не даст этого сделать и вернёт ошибку. 

Также мы определили что `ON DELETE CASCADE`. Это значит что если мы удалим овнера, то этот запрос также автоматически удалит и всех петов, которые сслыались на этого овнера. Есть и другие варианты `ON DELETE`, например `SET NULL`. 

Поиграться можно в локальной базе или на [dbfiddle](https://www.db-fiddle.com/).

2023-04-07 19:27 UTC, s3rius commented on project1/main.py
>      user = {username:password}
Зачем тебе здесь возвращать пользователя? У тебя при вызове этой функции и так будет пароль. Лучше сделать её просто валидирующей пароли. И тогда использоваться она будет прмиерно так:

```python
if not verify_password(password, hashed_password):
    raise HTTPException(401)

...
```

2023-04-07 19:27 UTC, s3rius commented on project1/main.py
> +                headers={"WWW-Authenticate": "Bearer"},
Этот хедер отправляется чуток при другой ситуаци. Этот хедер означает что требовался хедер Authorization и он не был предоставлен или был предоставлен некорректный. Насчёт второго случая не уверен.

2023-04-07 19:27 UTC, s3rius commented on project1/main.py
> +    print(user)
Попался принтик.

2023-04-07 19:27 UTC, s3rius commented on project1/main.py
> +                    FOREIGN_KEY VARCHAR)
Чтобы на инсерте достать ID достаточно сделать RETURNING. Если попробовать на примере выше, то будет примерно так:

```sql
INSERT INTO pet_owner(name) VALUES ('eeqw') RETURNING id;
```

Этот запрос вернёт тебе id пользователя, который он сгенерировал на вставке.

2023-04-08 15:05 UTC, KaplinY commented on project1/main.py
>      user = {username:password}
Я тут возвращаю пользователя, чтобы потом, если ничего не вернулось, выдать ошибку: detail="Incorrect username or password"

2023-04-08 15:05 UTC, KaplinY commented on project1/main.py
> +    print(user)
это я смотрел что там вообще у меня приходит и забыл удалить

2023-04-09 01:06 UTC, KaplinY commented on project1/main.py
> +                headers={"WWW-Authenticate": "Bearer"},
Эту часть я просто у tiangolo взял

2023-04-09 01:09 UTC, KaplinY commented on project1/main.py
> +                    FOREIGN_KEY VARCHAR)
job's done

2023-04-12 08:25 UTC, s3rius commented on project1/main.py
>      user = {username:password}
Ну, так у тебя всего 2 состояния. Либо пароль правильный, либо нет. Поэтому вполне логично тут возвращать boolean. Если ты будешь возвращать пользователя, то это просто лишняя аллокация. 

Причём этот объект пользователя не сказать чтобы был тебе нужен. Так как внутри там нет никакой дополнительной информации, кроме той, которую тебе передали в функцию.

2023-04-13 16:27 UTC, KaplinY commented on project1/main.py
>      user = {username:password}
Готово

2023-04-13 17:41 UTC, s3rius approved these changes
LGTM!

2023-04-13 17:57 UTC, merged