Aio pika
KaplinY/Python-puzzles pull request #23
Opened 2023-07-04 01:06 UTC by KaplinY

2023-07-04 22:22 UTC, s3rius requested changes
Смотри. Ты не добавил rabbitmq в docker-compose, поэтому у тебя скорее всего не будет коннектится ни к чему.

Также сам скрипт у тебя не запускается, так как тут только объявление функции, но нет её запуска. Должно быть примерно так:

```python
import asyncio

async def meme():
    await asyncio.sleep(1)

if __name__ == "__main__":
    asyncio.run(meme())

```

Вот в этой meme надо будет добавить всю логику. Также перемести сам скрипт ближе к корневой папке, так как он ничего общего с API не имеет. Да, он слушает сообщения, которые приходят от API, но по факту это отдельно работающее приложение должно быть.

Его надо будет добавить в docker-compose почти также как мигратор, только он будет запускать команду `python <script's path>.py`.

2023-07-04 22:22 UTC, s3rius commented on project1/db/migrations/versions/ebce488c9525_.py
> +    sa.Column('email', sa.Text(), nullable = False),
Никогда не модифицируй сществующие миграции. Добавляй новые через `alembic revision --autogenerate`.

2023-07-04 22:22 UTC, s3rius commented on project1/db/migrations/env.py
> +DB_DSN = "postgresql+asyncpg://percents:percents@database:5432/percents"
Оставь ENV, так как иначе это будет строка, которую нельзя будет конфигурировать. Так нельзя, потому что надо будет менять код чтобы применить миграции на существующую базу данных.

2023-07-04 22:22 UTC, s3rius commented on project1/api/users/views.py
> +    connection = await connect("amqp://guest:guest@localhost/")
Если будешь делать connect на каждый запрос, то это ооочень сильно замедлит сервис. Плюс, в либе есть такая штука как `connect_robust`, которая сама реконнекты обрабатывает и всё такое. 

Старайся все такие штуки пихать в startup, а использовать в обработчиках запросов уже инициализированные штуки. Помнишь, как мы базу выносили в стартап?

2023-07-04 22:22 UTC, s3rius commented on project1/api/users/consumer.py
> +async def main(session: AsyncSession = Depends(get_async_session)) -> None:
Тут не может быть dependency. Это чисто прикол FastAPI. С обычными python функциями оно не работает.

2023-07-04 22:22 UTC, s3rius commented on project1/api/users/consumer.py
> +        return(result)
![image](https://github.com/KaplinY/Python-Project/assets/18153319/8f90284e-4770-463d-b843-837dea936323)

2023-07-04 22:22 UTC, s3rius commented on project1/api/users/consumer.py
> +        user_id = await queue.consume(on_message, no_ack=True)
Почитай документацию о consume получше и посмотри на примеры использования.

2023-07-20 00:56 UTC, KaplinY commented
Перенес объявление очереди на start up, добился того, что консьюмер работает и всё что надо считает. Пока что не сделал отправку мейла, но код накидал. Там есть такие строки: server = smtplib.SMTP('myserver'); server.sendmail(FROM, TO, email_message). Вот тут мне надо какой то сервер, чтобы посылать мейлы, а у меня нет такого

2023-07-21 23:51 UTC, s3rius requested changes

2023-07-21 23:51 UTC, s3rius commented on .github/workflows/tests.yml
> +        healthcheck:
В гитхабе healthcheck по-другому сделан (хз почему, правда). Погляди на postgres.

2023-07-21 23:51 UTC, s3rius commented on project1/consumer.py
> +    avg_percent = str(sum(percent)/len(percent))
Насчёт всех вычислений. Проблема в том, что ты делаешь это в питоне. Питон по природе своей язык медленный и вычислять что-то в нём долго. Я специально подобрал операции, которые можно вычислить прям в базе данных. Для этого тебе надо выполнить чуть более сложные запросы. Также старайся делать как можно меньше запросов. Например информация по subsctracted и по percent может быть получена одним запросом

```python
select(Percents_data.percent, Percents_data.subtracted).where(Percents_data.user_id == user_id)
```

Но так как postgresql позволяет выполнять некоторые вычисления призапросе данных, ты и вовсе можешь написать один запрос, который достанет тебе все нужные данные по процентам. Информацию по пользователю, как ни крути, а придётся достать отдельно.

2023-07-21 23:51 UTC, s3rius commented on project1/consumer.py
> +    subtracted.sort()
Никогда не делай такие операции в питонах. Если нужно что-то отсортировать из БД, используй `order_by` в запросе.

2023-07-21 23:51 UTC, s3rius commented on project1/consumer.py
> +    server = smtplib.SMTP("85.10.195.40",30025)
Тут, типа, чувствительные данные, как ихназывают. Используй env.

2023-07-21 23:51 UTC, s3rius commented on project1/consumer.py
> +    # async def consume() -> None:
Попавлся мёртвый код.

2023-07-22 05:04 UTC, KaplinY commented on .github/workflows/tests.yml
> +        healthcheck:
Это я взял у какого то чувака. Да, у postgres по другому написано, но я чет не нашел так же для rabbitmq

2023-07-22 05:06 UTC, KaplinY commented on project1/consumer.py
> +    avg_percent = str(sum(percent)/len(percent))
SQL функции добавил, но у меня почему что не получилось доставать из разных columns данные через запятую. Он мне возвращает только первое значение, а остальные игнорит, хотя я делал scalars(stmt) и потом fetchall().

2023-07-22 05:06 UTC, KaplinY commented on project1/consumer.py
> +    subtracted.sort()
Done

2023-07-22 05:06 UTC, KaplinY commented on project1/consumer.py
> +    server = smtplib.SMTP("85.10.195.40",30025)
Done

2023-07-22 05:07 UTC, KaplinY commented on project1/consumer.py
> +    # async def consume() -> None:
Done

2023-07-22 09:48 UTC, s3rius requested changes

2023-07-22 09:48 UTC, s3rius commented on project1/consumer.py
> +    stmt = select(Percents_data.subtracted).where(Percents_data.user_id == user_id).group_by(Percents_data.subtracted)
Это тоже должно быть функцией SQL.

2023-07-22 09:48 UTC, s3rius commented on project1/consumer.py
> +    stmt = select(func.count(Percents_data.percent)).where(Percents_data.user_id == user_id)
Эти значения можно достать однимзапросом. Тебе не за чем выполнять несколько. 

```python
select(func.avg(Percents_data.percent), func.count(Percents_data.percent)).where(Percents_data.user_id == user_id)
```

Также сюда можно добавить и вычисления медианы.

2023-07-22 09:48 UTC, s3rius commented on project1/consumer.py
> +    stmt = select(Percents_data.subtracted).where(Percents_data.user_id == user_id).group_by(Percents_data.subtracted)
Group by не равно order by. Группировка собирает группы, но не сортирует.

2023-07-22 09:56 UTC, s3rius commented on project1/consumer.py
> +    avg_percent = str(sum(percent)/len(percent))
Попробуй без scalars. Должно сработать.

2023-07-22 09:57 UTC, s3rius commented on .github/workflows/tests.yml
> +        healthcheck:
Не, я про синтаксис. У тебя healthcheck определён отедельным объектом yaml, а в github это делается через options.

2023-07-23 01:05 UTC, KaplinY commented on .github/workflows/tests.yml
> +        healthcheck:
Понял, сделал так же как у постгреса

2023-07-23 16:17 UTC, merged