Feature/databases
KaplinY/Python-puzzles pull request #4
Opened 2023-03-18 15:22 UTC by KaplinY

2023-03-20 16:53 UTC, s3rius requested changes

2023-03-20 16:53 UTC, s3rius commented on project1/main.py
> +    with psycopg.connect("dbname=percents user=postgres password=postgres") as conn:
Вынеси в переменные среды строку для подключения. Плюс ты не указываешь куда на самом деле надо подключатся.  Так как адреса нет. Тут только название базы, юзер и пароль.

```python
import os

DB_DSN = os.environ.get("DB_DSN")

...

    with psycopg.connect(DB_DSN) as conn:
```

В докере приложению тогда надо будет добавить environment DB_DSN. 

Формат у этой строки должен быть примерно такой:

`postgresql://{username}:{password}@{host}:{port}/{db_name}` Например:  `postgresql://user:password@my-db.com:5432/my_lovely_base`.

2023-03-20 16:53 UTC, s3rius commented on project1/main.py
> +    with psycopg.connect("dbname=percents user=postgres password=postgres") as conn:
Тут тоже надо будет заменить на переменную. Чтоб не писать по два раза одно и то же. [DRY](https://www.baeldung.com/cs/dry-software-design-principle), как говорится.

2023-03-20 18:47 UTC, KaplinY commented on project1/main.py
> +    with psycopg.connect("dbname=percents user=postgres password=postgres") as conn:
done, но у меня такой вопрос: зачем здесь метод get? я так понимаю, что метод get возвращает значение по ключу в dictionary?

2023-03-20 21:12 UTC, s3rius requested changes

2023-03-20 21:12 UTC, s3rius commented on project1/main.py
> +DB_DSN = os.environ.get("postgresql://postgres:postgres@localhost:5432/percents")
Так погоди. environ это словарь. Там у тебя есть ключи это названия переменных. 

В данном случае ты пробуешь достать из переменных среды переменную с таким названием:
postgresql://postgres:postgres@localhost:5432/percents. 

А это маленько неудобно устанавливать и чутка неочевидно. Поэтому лучше поменяй назвние на какое-то более понятное, например `DB_DSN` или `DATABASE_URL` или ещё как. Главное чтобы было удобно её устанавливать. Если ты хочешь чтобы у тебя было дефолтное значение для твоей переменной и там лежала эта строка, то посмотри документацию к этому методу в стандартной библиотеке.

2023-03-20 21:13 UTC, s3rius commented on project1/main.py
> +    with psycopg.connect("dbname=percents user=postgres password=postgres") as conn:
Да, так и есть. В целом ты можешь использовать [""] что наверное будет более логично, так как без этой переменной среды приложение запускаться на должно.

НО! У get есть и другая возможность. Ты можешь вернуть какое-то значение по-умолчанию, если такого ключа нет.

2023-03-22 16:17 UTC, KaplinY commented
Я поменял main и добавил .env, но вот почему то у меня не получается сделать так, чтобы gitignore работал. У меня .env, и database.ini в gitignore добавлены, но все равно пушатся. Ну и я сделал не os.environ.get, а os.getenv, вроде работает.

2023-03-22 21:40 UTC, s3rius commented
@KaplinY, у тебя .gitignore чутка неверно написано. В целом правильно, но там лишние подчёркивания. Попробуй поменять на вот такое. 

```gitignore
/.env
/database.ini
```

Также не забудь удалить из индекса через `git rm --cached`. Если забудешь --cached, вроде как удалится файл реально. 

```bash
git rm --cached .env database.ini
```

Ну и потом commit + push.

2023-03-22 21:41 UTC, s3rius commented
Энивей, а зачем тебе database.ini? Его я думаю можно полностью удалить.

2023-03-22 21:49 UTC, s3rius approved these changes
Удали ненужные файлы и мержи в master.

2023-03-22 23:21 UTC, merged

2023-03-22 23:21 UTC, KaplinY commented
done